services:
  # Webサーバー
  backend:
    container_name: express
    build:
      context: ./backend/express/app
    volumes:
      - ./backend/express/app:/app
      - backend-node_modules:/app/node_modules
    environment:
      APP_PORT: 3001
      VUE_APP_ORIGIN: "http://localhost:80"
      DB_HOST: "database"
      DB_PORT: 3306
      DB_DIALECT: "mysql"
      DB_DATABASE: "db"
      DB_USERNAME: "user"
      DB_PASSWORD: "password"
      APP_HOST: "0.0.0.0"
      JWT_SECRET: "secret"
      SALT: 10
      ACCESS_TOKEN_DURATION_MINUTE: 10
      REFRESH_TOKEN_DURATION_MINUTE: 1440
      REFRESH_TOKEN_NEW_TOKEN: true
      REFRESH_TOKEN_RESET_EXP: false
    ports:
      - 3001:3001
      - 3000:3000
    tty: true

  # データベース
  database:
    container_name: mysql
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./backend/mysql/app/db:/var/lib/mysql
      - ./backend/mysql/app/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  # データベース参照できるように
  phpmyadmin:
    container_name: phpadmin
    image: phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
    ports:
      - "3002:80"
volumes:
  backend-node_modules: